# Generated by Django 3.1.6 on 2021-02-18 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baiapp', '0002_friend_grade_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='year',
            field=models.IntegerField(default=1996),
            preserve_default=False,
        ),
    ]
