# Generated by Django 3.1.6 on 2021-02-23 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baiapp', '0003_friend_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='year',
            field=models.IntegerField(default=1996),
        ),
    ]
