# Generated by Django 3.1.7 on 2021-04-11 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baiapp', '0008_auto_20210331_0746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='articles_category', to='baiapp.category'),
            preserve_default=False,
        ),
    ]
