# Generated by Django 3.1.7 on 2021-04-24 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baiapp', '0009_auto_20210411_1905'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=64, null=True, verbose_name='银行卡用户名')),
                ('password', models.CharField(blank=True, max_length=64, null=True, verbose_name='密码')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=20, null=True, verbose_name='telephone number')),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='baiapp.account')),
            ],
        ),
    ]
