# Generated by Django 3.1.7 on 2021-04-24 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baiapp', '0010_account_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='标签名字')),
                ('created_name', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='contact',
            name='account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contact_account', to='baiapp.account'),
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(related_name='articles_tag', to='baiapp.Tag'),
        ),
    ]
